### ISSUE TITLE
kubectl exec进入容器夯住（跨网段访问）

### ISSUE THREAD

**Issue by pigtool198122** [BurlyLuo/wcni-kind#2]
问题：flannel-vxlan-directrouting（跨网段）不能协商TSL协议1.3，导入不能进入业务pod，但是同网段是可以
描述：
如图所示

![Image](https://github.com/user-attachments/assets/ab25c1d7-6b30-4012-b491-c8da6e78e548)
抓包：

![Image](https://github.com/user-attachments/assets/9c745b04-2fd8-4a25-a0d1-7e5ba2ca5ba7)
有问题日志：

![Image](https://github.com/user-attachments/assets/e208ef35-b5a4-42a2-8ceb-554bf553c9f4)

![Image](https://github.com/user-attachments/assets/883535c8-a33c-461b-a16f-41bec8885403)
备注：
是不是vyos 不支持高版本TLS1.3， 适配自动降低版本TLS1.2， 协商后的低版本TLS无法建立会话，导致跨设备异常

**Comment by pigtool198122** [comment]
vyos是不是需要指定一下版本？

**Comment by BurlyLuo** [comment]
![Image](https://github.com/user-attachments/assets/eb7b7d2d-ea79-4b40-97a3-5a1f2481a2f9)
原因是由于创建的server容器的网卡的mtu是9500. 所以当在发的包的length超过1500的时候，对与本端来说是不需要分片的，所以：
```
Frame 7: 2441 bytes on wire (19528 bits), 2441 bytes captured (19528 bits)
Ethernet II, Src: Containerlab_d6:66:f1 (aa:c1:ab:d6:66:f1), Dst: Containerlab_ce:78:9a (aa:c1:ab:ce:78:9a)
Internet Protocol Version 4, Src: 10.1.8.11, Dst: 10.1.5.10
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 2427
    Identification: 0xa7ef (42991)
    010. .... = Flags: 0x2, Don't fragment
        0... .... = Reserved bit: Not set
        .1.. .... = Don't fragment: Set   // 这里不允许分片
        ..0. .... = More fragments: Not set  // 没有新分片
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 64
    Protocol: TCP (6)
    Header Checksum: 0x6877 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 10.1.8.11
    Destination Address: 10.1.5.10
Transmission Control Protocol, Src Port: 10250, Dst Port: 58146, Seq: 1, Ack: 255, Len: 2375
    Source Port: 10250
    Destination Port: 58146
    [Stream index: 0]
    [Conversation completeness: Incomplete, DATA (15)]
    [TCP Segment Len: 2375]
    Sequence Number: 1    (relative sequence number)
    Sequence Number (raw): 3380513994
    [Next Sequence Number: 2376    (relative sequence number)]
    Acknowledgment Number: 255    (relative ack number)
    Acknowledgment number (raw): 3513780693
    1000 .... = Header Length: 32 bytes (8)
    Flags: 0x018 (PSH, ACK)
    Window: 441
    [Calculated window size: 56448]
    [Window size scaling factor: 128]
    Checksum: 0xce25 [unverified]
    [Checksum Status: Unverified]
    Urgent Pointer: 0
    Options: (12 bytes), No-Operation (NOP), No-Operation (NOP), Timestamps
    [Timestamps]
    [SEQ/ACK analysis]
    TCP payload (2375 bytes)
    Retransmitted TCP segment data (2375 bytes)

```
而中间的vyos路由器的接口mtu是1500.当收到这样的数据包就会被丢弃了。从而导致 ```6	2025-01-17 19:27:41.942856	10.1.8.11	10.1.5.10	TLSv1.3	2441	0xa7ee (42990)	1	2375	255	2376	10250	58146	0	Server Hello, Change Cipher Spec, Application Data, Application Data, Application Data, Application Data, Application Data```
重传。

所以我们需要把serverx的网卡的mtu设置为1500.
```

  links:
    - endpoints: ["br-pool0:br-pool0-net0", "server1:net0"]
      mtu: 1500
    - endpoints: ["br-pool0:br-pool0-net1", "server2:net0"]
      mtu: 1500
    - endpoints: ["br-pool1:br-pool1-net0", "server3:net0"]
      mtu: 1500
    - endpoints: ["br-pool1:br-pool1-net1", "server4:net0"]
      mtu: 1500

    - endpoints: ["gw0:eth1", "br-pool0:br-pool0-net2"]
      mtu: 1500
    - endpoints: ["gw0:eth2", "br-pool1:br-pool1-net2"]
      mtu: 1500
EOF
```
应用配置以后，重新部署。问题解决。
